# Generated by Django 4.1.7 on 2023-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='LabelCreateFormName')),
                ('color', models.CharField(choices=[('secondary', 'Grey'), ('success', 'Green'), ('primary', 'Blue'), ('danger', 'Red')], default='secondary', max_length=9, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
