# Generated by Django 4.1.7 on 2023-03-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(choices=[('secondary', 'Gray'), ('success', 'Green'), ('primary', 'Blue'), ('danger', 'Red')], default='secondary', max_length=9, verbose_name='LabelCreateFormColor'),
        ),
    ]
