# Generated by Django 4.1.7 on 2023-03-12 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='TaskCreateFormName')),
                ('description', models.TextField(max_length=200, verbose_name='TaskCreateFormDescription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_of_task', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor_of_task', to=settings.AUTH_USER_MODEL, verbose_name='TaskCreateFormExecutor')),
                ('labels', models.ManyToManyField(blank=True, to='labels.label', verbose_name='TaskCreateFormLabels')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.status', verbose_name='TaskCreateFormStatus')),
            ],
        ),
    ]
