# Generated by Django 4.1.7 on 2023-03-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='performer',
        ),
    ]
